export const STRINGS = {
  COMPOSER: {
    LOGIN_TITLE: '請先登入',
    LOGIN_DESC: '登入後即可參與討論與發布貼文',
    CANCEL: '取消',
    GO_LOGIN: '前往登入',
    TITLE_PRIVATE: '🔐 私密貼文',
    TITLE_PUBLIC: '✏️ 發布貼文',
    CLOSE: '關閉',
    CLOSE_ICON: '✕',
    VISIBILITY_PUBLIC: '🌍 公開牆',
    VISIBILITY_PRIVATE: '🔐 住戶專屬',
    PLACEHOLDER_COMMUNITY_PRIVATE: '分享只有住戶能看到的內容...',
    PLACEHOLDER_COMMUNITY_PUBLIC: '分享你的想法、社區生活...',
    PLACEHOLDER_FEED: '分享你的新鮮事...',
    UPLOAD_IMAGE: '📷 上傳圖片',
    UPLOAD_IMAGE_DEV: '圖片上傳功能開發中',
    SUBMIT: '發布',
    SUBMITTING: '發布中...',
    SUCCESS: '發布成功！',
    ERROR_TITLE: '發布失敗',
  },
  COMMUNITY: {
    AGENT_BADGE: '認證房仲',
    OFFICIAL_BADGE: '官方公告',
    RESIDENT_BADGE_SUFFIX: ' 住戶',
    PRIVATE_POST_LABEL: '僅社區可見',
    BTN_MSG_AGENT: '私訊房仲',
    BTN_LIKE: '讚',
    BTN_LIKING: '處理中',
    BTN_REPLY: '回覆',
    BTN_REPLY_TOOLTIP: '功能開發中，敬請期待',
    BTN_REPLY_ARIA: '回覆功能開發中',
    BTN_POST_PUBLIC: '發布貼文',
    BTN_POST_PRIVATE: '發布私密貼文',
    SECTION_TITLE: '社區熱帖',
    TAB_PUBLIC: '公開牆',
    TAB_PRIVATE: '私密牆',
    MSG_AGENT_VIEW_ONLY: '房仲可查看私密牆，但無法發文',
    LOCKED_TITLE: '私密牆僅限本社區住戶查看',
    LOCKED_DESC_GUEST: '請先登入或註冊',
    LOCKED_DESC_USER: '驗證住戶身份後即可加入討論',
    BTN_UNLOCK_GUEST: '免費註冊 / 登入',
    BTN_UNLOCK_USER: '我是住戶，驗證身份',
    NOTIFY_LOGIN_TITLE: '請先登入或註冊',
    NOTIFY_LOGIN_DESC: '登入後才能發布貼文',
    NOTIFY_PERM_ERROR: '目前無法發文',
    NOTIFY_PERM_CHECK: '請確認帳號權限或稍後再試',
    NOTIFY_PRIVATE_ONLY: '僅住戶可發佈私密貼文',
    NOTIFY_PRIVATE_ACCESS_DENIED: '請先登入或註冊',
    NOTIFY_PRIVATE_ACCESS_DENIED_DESC: '登入/註冊後可查看私密牆',
    NOTIFY_VERIFY_REQUIRED: '請完成住戶驗證',
    NOTIFY_VERIFY_REQUIRED_DESC: '上傳水電帳單或管理費收據後即可查看',
    LOCKED_OVERLAY_COUNT_LABEL: '則貼文',
    LOCKED_OVERLAY_BENEFIT_1: '查看完整動態',
    LOCKED_OVERLAY_BENEFIT_2: '新回應通知',
  },
  VALIDATION: {
    MIN_LENGTH: (min: number) => `內容至少需要 ${min} 個字`,
    MAX_LENGTH: (max: number) => `內容不能超過 ${max} 個字`,
    SUBMIT_ERROR: '發布失敗',
  },
  WALL_STATES: {
    ERROR_TITLE: '發生錯誤',
    ERROR_DEFAULT: '載入失敗，請稍後再試',
    RETRY: '重試',
    EMPTY_TITLE: '這裡空空的',
    EMPTY_DEFAULT: '目前沒有任何貼文',
    LOADING_LABEL: '載入中...',
  },
};

