export const STRINGS = {
  FEED: {
    TITLE: '我的社區',
    PAGE_TITLE: '邁房子｜我的社區',
    PROFILE: {
      STATS_DAYS: '互動天數',
      STATS_LIKED: '被感謝',
      STATS_CONTRIB: '貢獻篇數',
      // New keys
      LEVEL_RESIDENT: '黃金住戶',
      LEVEL_AGENT: '認證房仲',
      LEVEL_MEMBER: '社區成員',
      FROM: (name: string) => `來自【${name}】`,
      FROM_MY_COMMUNITY: '來自【我的社區】',
      VIEW_WALL: '🧱 查看我的社區牆',
    },
    TX_BANNER: {
      TITLE: '您有一筆交易進行中',
      ENTER_BTN: '進入戰情室',
    },
    SIDEBAR: {
      NAV_TITLE: '快速導航',
      HOT_TITLE: '社區動態',
      SALE_TITLE: '待售物件',
      VIEW_ALL: '查看全部',
      HOT_EMPTY: '暫無熱門貼文',
      SALE_EMPTY: '暫無待售物件',
      // New keys
      HOT_NEW_POSTS: '本週新增',
      HOT_POSTS_UNIT: '篇貼文',
      HOT_ACTIVE_COMMUNITIES: '活躍社區',
      HOT_COMMUNITIES_UNIT: '個',
      SALE_PREFIX: '目前有',
      SALE_SUFFIX: '戶待售',
    },
    POST: {
      LIKE_BTN: '讚',
      LIKED_BTN: '已讚',
      REPLY_BTN: '回覆',
      SHARE_BTN: '分享',
      SHOW_MORE: '查看更多',
      SHOW_LESS: '收起',
      TIME_JUST_NOW: '剛剛',
      TIME_MINUTES_AGO: (n: number) => `${n} 分鐘前`,
      TIME_HOURS_AGO: (n: number) => `${n} 小時前`,
      TIME_DAYS_AGO: (n: number) => `${n} 天前`,
      // New keys
      BADGE_AGENT: '房仲',
      BADGE_OFFICIAL: '公告',
      VIEWS: (n: number) => `${n} 次瀏覽`,
      PINNED: '可預約看屋',
    },
    AI_INSIGHT: {
      TITLE: 'AI 社區洞察',
      PUBLIC_RATIO: '公開討論比例',
      COMMUNITY_RATING: '社區評分',
      ACTIVITY_SCORE: '活躍度',
    },
    NAV: {
      HOME: '首頁',
      COMMUNITY: '我的社區',
      NOTIFICATIONS: '通知',
      PROFILE: '個人',
    },
    EMPTY: {
      TITLE: '還沒有貼文',
      DESC: '成為第一個發布貼文的人吧！',
    },
    ERROR: {
      LOAD_FAILED: '載入失敗',
      RETRY: '重試',
    },
  },
  COMPOSER: {
    LOGIN_TITLE: '請先登入',
    LOGIN_DESC: '登入後即可參與討論與發布貼文',
    CANCEL: '取消',
    GO_LOGIN: '前往登入',
    TITLE_PRIVATE: '🔐 私密貼文',
    TITLE_PUBLIC: '✏️ 發布貼文',
    CLOSE: '關閉',
    CLOSE_ICON: '✕',
    VISIBILITY_PUBLIC: '🌍 公開牆',
    VISIBILITY_PRIVATE: '🔐 住戶專屬',
    PLACEHOLDER_COMMUNITY_PRIVATE: '分享只有住戶能看到的內容...',
    PLACEHOLDER_COMMUNITY_PUBLIC: '分享你的想法、社區生活...',
    PLACEHOLDER_FEED: '分享你的新鮮事...',
    UPLOAD_IMAGE: '📷 上傳圖片',
    UPLOAD_IMAGE_DEV: '圖片上傳功能開發中',
    SUBMIT: '發布',
    SUBMITTING: '發布中...',
    SUCCESS: '發布成功！',
    ERROR_TITLE: '發布失敗',
  },
  COMMUNITY: {
    AGENT_BADGE: '認證房仲',
    OFFICIAL_BADGE: '官方公告',
    RESIDENT_BADGE_SUFFIX: ' 住戶',
    PRIVATE_POST_LABEL: '僅社區可見',
    BTN_MSG_AGENT: '私訊房仲',
    BTN_LIKE: '讚',
    BTN_LIKING: '處理中',
    BTN_REPLY: '回覆',
    BTN_REPLY_TOOLTIP: '功能開發中，敬請期待',
    BTN_REPLY_ARIA: '回覆功能開發中',
    BTN_POST_PUBLIC: '發布貼文',
    BTN_POST_PRIVATE: '發布私密貼文',
    SECTION_TITLE: '社區熱帖',
    TAB_PUBLIC: '公開牆',
    TAB_PRIVATE: '私密牆',
    MSG_AGENT_VIEW_ONLY: '房仲可查看私密牆，但無法發文',
    LOCKED_TITLE: '私密牆僅限本社區住戶查看',
    LOCKED_DESC_GUEST: '請先登入或註冊',
    LOCKED_DESC_USER: '驗證住戶身份後即可加入討論',
    BTN_UNLOCK_GUEST: '免費註冊 / 登入',
    BTN_UNLOCK_USER: '我是住戶，驗證身份',
    NOTIFY_LOGIN_TITLE: '請先登入或註冊',
    NOTIFY_LOGIN_DESC: '登入後才能發布貼文',
    NOTIFY_PERM_ERROR: '目前無法發文',
    NOTIFY_PERM_CHECK: '請確認帳號權限或稍後再試',
    NOTIFY_PRIVATE_ONLY: '僅住戶可發佈私密貼文',
    NOTIFY_PRIVATE_ACCESS_DENIED: '請先登入或註冊',
    NOTIFY_PRIVATE_ACCESS_DENIED_DESC: '登入/註冊後可查看私密牆',
    NOTIFY_VERIFY_REQUIRED: '請完成住戶驗證',
    NOTIFY_VERIFY_REQUIRED_DESC: '上傳水電帳單或管理費收據後即可查看',
    LOCKED_OVERLAY_COUNT_LABEL: '則貼文',
    LOCKED_OVERLAY_BENEFIT_1: '查看完整動態',
    LOCKED_OVERLAY_BENEFIT_2: '新回應通知',
  },
  VALIDATION: {
    MIN_LENGTH: (min: number) => `內容至少需要 ${min} 個字`,
    MAX_LENGTH: (max: number) => `內容不能超過 ${max} 個字`,
    SUBMIT_ERROR: '發布失敗',
  },
  WALL_STATES: {
    ERROR_TITLE: '發生錯誤',
    ERROR_DEFAULT: '載入失敗，請稍後再試',
    RETRY: '重試',
    EMPTY_TITLE: '這裡空空的',
    EMPTY_DEFAULT: '目前沒有任何貼文',
    LOADING_LABEL: '載入中...',
  },
};

